### ISSUE TITLE
Точно ли double?

### ISSUE THREAD

**Issue by coursar** [Artyom16RUS/Fuel-rating#1]
https://github.com/Artyom16RUS/Fuel-rating/blob/51e785970e1f080c86c9867fb41304e24f9c90a2/src/Main.java#L12

**Comment by Artyom16RUS** [comment]
I changed **_double_** to **_int_**. 

- I agree, the tank volume is measured in whole numbers

**Comment by coursar** [comment]
Если сделали, закрывайте issue
